# Generated by Django 3.0.7 on 2020-08-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_in_book',
            field=models.IntegerField(default=0),
        ),
    ]
