# Generated by Django 3.0.4 on 2020-04-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='denom1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom10',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom100',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom2',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom20',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom200',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom5',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom50',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom500',
        ),
    ]
