# Generated by Django 3.0.4 on 2020-04-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200407_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='denom1',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom10',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom2',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom20',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom5',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom50',
        ),
    ]
