# Generated by Django 3.0.4 on 2020-04-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200407_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
