# Generated by Django 3.0.4 on 2020-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_payment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='denom100',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='denom200',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='denom2000',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='denom500',
            field=models.IntegerField(default=0),
        ),
    ]
