# Generated by Django 3.0.4 on 2020-05-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
    ]
