# Generated by Django 3.0.4 on 2020-05-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_bill_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
