# Generated by Django 3.0.4 on 2020-05-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_bill_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
