# Generated by Django 3.0.4 on 2020-05-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_particular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Product'),
        ),
        migrations.AlterField(
            model_name='particular',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
