# Generated by Django 3.0.4 on 2020-05-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20200520_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='particular',
            name='rate_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Rate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='particular',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
