# Generated by Django 3.0.4 on 2020-05-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20200520_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='product',
        ),
        migrations.AddField(
            model_name='rate',
            name='product',
            field=models.ManyToManyField(to='home.Product'),
        ),
    ]
