# Generated by Django 3.0.4 on 2020-05-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20200526_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='product',
        ),
    ]
