# Generated by Django 3.0.4 on 2020-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
