# Generated by Django 3.0.4 on 2020-05-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='denom100',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom200',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom2000',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='denom500',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
