# Generated by Django 3.0.4 on 2020-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_payment_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
