# Generated by Django 3.0.7 on 2020-06-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20200609_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.AlterField(
            model_name='payment',
            name='intrest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
